// 标识此文件使用的语法版本是protobuf3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.3
// source: embed.proto

package embed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbReqData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []int32 `protobuf:"varint,1,rep,packed,name=Keys,proto3" json:"Keys,omitempty"`
}

func (x *EmbReqData) Reset() {
	*x = EmbReqData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embed_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbReqData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbReqData) ProtoMessage() {}

func (x *EmbReqData) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbReqData.ProtoReflect.Descriptor instead.
func (*EmbReqData) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{0}
}

func (x *EmbReqData) GetKeys() []int32 {
	if x != nil {
		return x.Keys
	}
	return nil
}

// 定义响应结构体
type EmbResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmbVectors []*EmbVector `protobuf:"bytes,1,rep,name=EmbVectors,proto3" json:"EmbVectors,omitempty"`
}

func (x *EmbResp) Reset() {
	*x = EmbResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embed_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbResp) ProtoMessage() {}

func (x *EmbResp) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbResp.ProtoReflect.Descriptor instead.
func (*EmbResp) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{1}
}

func (x *EmbResp) GetEmbVectors() []*EmbVector {
	if x != nil {
		return x.EmbVectors
	}
	return nil
}

type EmbVector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []float32 `protobuf:"fixed32,1,rep,packed,name=Element,proto3" json:"Element,omitempty"`
}

func (x *EmbVector) Reset() {
	*x = EmbVector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_embed_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbVector) ProtoMessage() {}

func (x *EmbVector) ProtoReflect() protoreflect.Message {
	mi := &file_embed_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbVector.ProtoReflect.Descriptor instead.
func (*EmbVector) Descriptor() ([]byte, []int) {
	return file_embed_proto_rawDescGZIP(), []int{2}
}

func (x *EmbVector) GetElement() []float32 {
	if x != nil {
		return x.Element
	}
	return nil
}

var File_embed_proto protoreflect.FileDescriptor

var file_embed_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a,
	0x0a, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x71, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x4b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x22,
	0x35, 0x0a, 0x07, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2a, 0x0a, 0x0a, 0x45, 0x6d,
	0x62, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x45, 0x6d, 0x62, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0a, 0x45, 0x6d, 0x62, 0x56,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x25, 0x0a, 0x09, 0x45, 0x6d, 0x62, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x02, 0x52, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x2c, 0x0a,
	0x09, 0x45, 0x6d, 0x62, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x06, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x12, 0x0b, 0x2e, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x71, 0x44, 0x61, 0x74,
	0x61, 0x1a, 0x08, 0x2e, 0x45, 0x6d, 0x62, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2e, 0x2f, 0x3b, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_embed_proto_rawDescOnce sync.Once
	file_embed_proto_rawDescData = file_embed_proto_rawDesc
)

func file_embed_proto_rawDescGZIP() []byte {
	file_embed_proto_rawDescOnce.Do(func() {
		file_embed_proto_rawDescData = protoimpl.X.CompressGZIP(file_embed_proto_rawDescData)
	})
	return file_embed_proto_rawDescData
}

var file_embed_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_embed_proto_goTypes = []interface{}{
	(*EmbReqData)(nil), // 0: EmbReqData
	(*EmbResp)(nil),    // 1: EmbResp
	(*EmbVector)(nil),  // 2: EmbVector
}
var file_embed_proto_depIdxs = []int32{
	2, // 0: EmbResp.EmbVectors:type_name -> EmbVector
	0, // 1: EmbServer.Lookup:input_type -> EmbReqData
	1, // 2: EmbServer.Lookup:output_type -> EmbResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embed_proto_init() }
func file_embed_proto_init() {
	if File_embed_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_embed_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbReqData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embed_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_embed_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbVector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_embed_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embed_proto_goTypes,
		DependencyIndexes: file_embed_proto_depIdxs,
		MessageInfos:      file_embed_proto_msgTypes,
	}.Build()
	File_embed_proto = out.File
	file_embed_proto_rawDesc = nil
	file_embed_proto_goTypes = nil
	file_embed_proto_depIdxs = nil
}
